# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The WebOps Club 
email: thewebopsclubiitm@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>The WebOps Club</h1><h3>Group of Developers at IIT Madras</h3>Come <a href=https://groups.google.com/forum/#!forum/webops-club-iitm/join target=_blank>join us!</a>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://the.webops.club" # the base hostname & protocol for your site
twitter_username: TheWebOpsClub 
github_username: the-webops-club 

# Build settings
markdown: kramdown
